### ISSUE TITLE
Installation script bug

### ISSUE THREAD

**Issue by ValtchanV** [MTG/gaia#1]
waf configure will sometimes fail due to _get_python_variables in (what looks like a generated file) .../wafadmin/Tools/python.py not supporting the strings returned from the script it executes being wrapped in " instead of '.

def _get_python_variables(python_exe,variables,imports=['import sys']):
 ...
        elif s[0]=="'"and s[-1]=="'":
            return_values.append(s[1:-1])
                #Possible Fix:
        elif s[0]=='"' and s[-1]=='"':
            return_values.append(s[1:-1])
.....

**Comment by alastair** [comment]
waf has been upgraded since this bug, closing because no one else has reported it.
