### ISSUE TITLE
Training with own datasets

### ISSUE THREAD

**Issue by mantree** [MTG/gaia#10]
I've been trying to figure out how i could use gaia with my own data to produce a classifier and i think i've come up against a road block.

When running generate_classification_project.py it bails out looking for 'stable/genre_tzanetakis/metadata/config.yaml'. I guess this is the file that configures the svm to produce the tzanetakis history file. An older version of which i've been able to make use of with essentia to classify my own tracks.

I can't find this configuration file in the repo, is it intentionally missing? If so, would it be possible to get an example of some kind i could start from to figure out how to get going?

**Comment by dbogdanov** [comment]
We have included scripts that facilitate the process of training models and will provide a documentation for using it soon. https://github.com/MTG/gaia/blob/master/src/bindings/pygaia/scripts/classification/train_model.py

**Comment by dbogdanov** [comment]
New section in [Essenita FAQ](https://github.com/MTG/essentia/blob/master/FAQ.md#training-and-running-classifier-models-in-gaia) explaines how to train your own models.
