### ISSUE TITLE
QT5.11 / C++11 changes

### ISSUE THREAD

**Issue by alastair** [MTG/gaia#101]
#92 upgraded to QT 5.9, in Ubuntu 18.04.

QT5.11 in Debian 10 requires c++11, this should be changed in the waffile

When upgrading to C++11, `gvarlengtharray.h` fails to compile because of the use of memcpy.
I see that this file appears to be an almost direct copy of [qvarlengtharray](https://doc.qt.io/qt-5/qvarlengtharray.html) from QT, and then renamed q->g. I'm not sure why it's been copied into the gaia code and renamed. @dbogdanov do you have any idea about this? It seems like we could just directly use qvarlengtharray here

We should also check on the latest QT, 5.14.

**Comment by alastair** [comment]
There are also a number of warnings now emitted by c++11 compilers, and additional warnings by newer versions of gcc and clang. We should try to reach 0 warnings during gaia compilation.

**Comment by dbogdanov** [comment]
Related to `gvarlengtharray.h`, at that time, there was some bug in QT 4.6 and for that reason a static version of QVarLengthArray from 4.5.3 was included into the source tree. This should be irrelevant now.
