### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by hugosoli** [MTG/gaia#113]
On Linux
If i try to compile gaia2 in python2 it fails.
If i try to compile gaia2 in python 3 it compiles but I run the tutorial and I got
NameError: name 'basestring' is not defined in many of the functions
On MAC with homebrew
If it try to compile bunch of problemas with dependiencies that seems to be outdated.

Anyidea what should I do to work with gaia2 :(

**Comment by alastair** [comment]
Hi,
We have some pending items to fix for python 3 support: #111 

If you want to run gaia in python 2, you can check out the tag v.2.4.6: https://github.com/MTG/gaia/releases/tag/v2.4.6

**Comment by alastair** [comment]
#111 has been merged, so now we only support python 3
