### ISSUE TITLE
Build files with swig 3.0.3 (osx yosemite)

### ISSUE THREAD

**Issue by ffont** [MTG/gaia#13]
Hey,
I realised building gaia fails on osx yosemite when using swig 3.0.3.
I had to rollback swig to 3.0.2 to fix the issue.

**Comment by ffont** [comment]
I pushed a fix for this issue in "fix_issue_13" branch.
Apparently swig's error reporting policy changed in swig>=3.0.3 (http://www.swig.org/Doc3.0/SWIGDocumentation.html#Python_nn42), and thus it started complaining about unknown SWIG preprocessor directives because of some comments in our source files using python syntax.
I applied fixes in src/bindings/frozendataset.i and src/bindings/pythonic.i so that gaia (with-python) complies with swig>=3.0.3.
Only tested on OSX yosemite.

**Comment by dbogdanov** [comment]
This fixes compilation but when using in python ```import gaia2``` fails because of "/* */"
