### ISSUE TITLE
Libs not found on MacOS X (Yosemite)

### ISSUE THREAD

**Issue by levivoelz** [MTG/gaia#15]
Hi,

Per the instructions, I installed packages via homebrew and am getting these results:
```shell
Setting top to                           : /Users/...
Setting out to                           : /Users/...
→ configuring the project in /Users/...
→ Building in release mode
Checking for program pkg-config          : /usr/local/bin/pkg-config 
Checking for 'yaml-0.1'                  : yes 
Checking for 'g++' (c++ compiler)        : clang++ 
Checking for 'gcc' (c compiler)          : clang 
Checking for program qmake-qt4           : not found 
Checking for program qmake4              : not found 
Checking for program qmake               : /usr/local/bin/qmake 
Checking for program uic-qt3             : not found 
Checking for program uic3                : not found 
Checking for program uic-qt4             : not found 
Checking for program uic                 : /usr/local/bin/uic 
Checking for uic version                 : version 4.8.6 
Checking for program moc-qt4             : not found 
Checking for program moc                 : /usr/local/bin/moc 
Checking for program rcc                 : /usr/local/bin/rcc 
Checking for program lrelease-qt4        : not found 
Checking for program lrelease            : /usr/local/bin/lrelease 
Checking for program lupdate-qt4         : not found 
Checking for program lupdate             : /usr/local/bin/lupdate 
Found the Qt4 libraries in               : /usr/local/Cellar/qt/4.8.6/lib 
Checking for pkg-config version >= '0.1' : yes 
Checking for 'QtCore_debug'              : not found 
Checking for 'QtGui_debug'               : not found 
Checking for 'QtUiTools_debug'           : yes 
Checking for 'QtNetwork_debug'           : not found 
Checking for 'QtOpenGL_debug'            : not found 
Checking for 'QtSql_debug'               : not found 
Checking for 'QtSvg_debug'               : not found 
Checking for 'QtTest_debug'              : not found 
Checking for 'QtXml_debug'               : not found 
Checking for 'QtXmlPatterns_debug'       : not found 
Checking for 'QtWebKit_debug'            : not found 
Checking for 'Qt3Support_debug'          : not found 
Checking for 'QtHelp_debug'              : not found 
Checking for 'QtScript_debug'            : not found 
Checking for 'QtDeclarative_debug'       : not found 
Checking for 'QtCore'                    : yes 
Checking for 'QtGui'                     : yes 
Checking for 'QtUiTools'                 : yes 
Checking for 'QtNetwork'                 : yes 
Checking for 'QtOpenGL'                  : yes 
Checking for 'QtSql'                     : yes 
Checking for 'QtSvg'                     : yes 
Checking for 'QtTest'                    : yes 
Checking for 'QtXml'                     : yes 
Checking for 'QtXmlPatterns'             : yes 
Checking for 'QtWebKit'                  : yes 
Checking for 'Qt3Support'                : not found 
Checking for 'QtHelp'                    : yes 
Checking for 'QtScript'                  : yes 
Checking for 'QtDeclarative'             : yes 
'configure' finished successfully (0.985s)
```
Of course, when I try to build, it fails. Is there another package I can install with the other QT libs? Any help is appreciated.

–Levi

**Comment by dbogdanov** [comment]
The "*_debug" libs are not necessary. Your configuration has finished successfully. What is the build error you get?

**Comment by levivoelz** [comment]
Hey @dbogdanov, I just tried again and it did build. No issue here. Thank you.

**Comment by yurci** [comment]
Hello I have exactly same libs missing. During compile i am getting this error:

[ 85/104] swig: src/bindings/gaia.swig -> build/src/bindings/gaia2.swigwrap_1.cxx build/src/bindings/gaia2.py
Assertion failed: (!Getattr(n, "defaultargs")), function update_defaultargs, file parser.y, line 667.
Waf: Leaving directory `/Users/Yurci/Documents/GIT/gaia/build'
Build failed
 -> task in '_gaia2' failed (exit status -6): 

Any suggestions?

**Comment by Declic73** [comment]
Same problem for me, tried to build on ubuntu 16.04 

→ Building in release mode
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for 'yaml-0.1'                  : yes 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for program 'qmake-qt4'         : /usr/bin/qmake-qt4 
**Checking for program 'qmake4'            : not found** 
Checking for program 'qmake'             : /usr/bin/qmake 
**Checking for program 'uic-qt3'           : not found** 
Checking for program 'uic3'              : /usr/bin/uic3 
Checking for program 'uic-qt4'           : /usr/bin/uic-qt4 
Checking for uic version                 : version 4.8.7 
Checking for program 'moc-qt4'           : /usr/bin/moc-qt4 
**Checking for program 'rcc-qt4'           : not found** 
Checking for program 'rcc'               : /usr/bin/rcc 
Checking for program 'lrelease-qt4'      : /usr/bin/lrelease-qt4 
Checking for program 'lupdate-qt4'       : /usr/bin/lupdate-qt4 
Found the Qt4 libraries in               : /usr/lib/x86_64-linux-gnu 
Checking for pkg-config version >= '0.1' : yes 
**Checking for 'QtCore_debug'              : not found 
Checking for 'QtGui_debug'               : not found 
Checking for 'QtUiTools_debug'           : not found 
Checking for 'QtNetwork_debug'           : not found 
Checking for 'QtOpenGL_debug'            : not found 
Checking for 'QtSql_debug'               : not found 
Checking for 'QtSvg_debug'               : not found 
Checking for 'QtTest_debug'              : not found 
Checking for 'QtXml_debug'               : not found 
Checking for 'QtXmlPatterns_debug'       : not found 
Checking for 'QtWebKit_debug'            : not found 
Checking for 'Qt3Support_debug'          : not found 
Checking for 'QtHelp_debug'              : not found 
Checking for 'QtScript_debug'            : not found 
Checking for 'QtDeclarative_debug'       : not found 
Checking for 'QtDesigner_debug'          : not found** 
Checking for 'QtCore'                    : yes 
Checking for 'QtGui'                     : yes 
Checking for 'QtUiTools'                 : yes 
Checking for 'QtNetwork'                 : yes 
Checking for 'QtOpenGL'                  : yes 
Checking for 'QtSql'                     : yes 
Checking for 'QtSvg'                     : yes 
Checking for 'QtTest'                    : yes 
Checking for 'QtXml'                     : yes 
Checking for 'QtXmlPatterns'             : yes 
Checking for 'QtWebKit'                  : yes 
Checking for 'Qt3Support'                : yes 
Checking for 'QtHelp'                    : yes 
Checking for 'QtScript'                  : yes 
Checking for 'QtDeclarative'             : yes 
Checking for 'QtDesigner'                : yes 
Checking for program 'swig'              : /usr/bin/swig 
Checking for program 'python'            : /usr/bin/python 
Checking for swig version                : 3.0.8 
Checking for python version              : (2, 7, 12, 'final', 0) 
python-config                            : /usr/bin/python-config 
Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes 
Testing pyembed configuration                                      : yes 
Asking python-config for pyext '--cflags --libs --ldflags' flags   : yes 
Testing pyext configuration                                        : yes 
'configure' finished successfully (0.773s)

And then when building it fails 85/104
[85/93] Processing src/bindings/gaia.swig
swig: parser.y:667: update_defaultargs: Assertion `!Getattr(n, "defaultargs")' failed.

**Comment by yurci** [comment]
Hello,

Downgrading swig to version 3.0.4 worked for me with a similar error. 

12 Ağu 2016 tarihinde 17:58 saatinde, Declic73 <notifications@github.com> şunları yazdı:
