### ISSUE TITLE
Install instructions for Mac OSX and linux may be a bit confusing

### ISSUE THREAD

**Issue by wolfchimneyrock** [MTG/gaia#25]
if you want to install gaia systemwide, 
shouldn't the install instructions line:
$ ./waf install [--destdir=/where/ever/]
actually be:
$ sudo ./waf install 

this worked for me after we had some hair pulling getting it working on mac OSX mavericks.

**Comment by dbogdanov** [comment]
[Commonly, square brackets are commonly used to indicate optional arguments](https://en.wikipedia.org/wiki/Usage_message), although indeed this might not be obvious for some of the users who are not used to work with the command-line syntax.
