### ISSUE TITLE
Various problems running the tests (files not found)

### ISSUE THREAD

**Issue by bxdpxndx** [MTG/gaia#3]
Hello, after downloading and installing the gaia library I wanted to run the tests. Unfortunately, I couldn't get them all to pass. I am getting errors like:

```
    testValues (test_merge.TestMerge) ... Could not read from file: "data/dataset_small/Techno and Electro/01 Bigmouth.mp3.sig"
    Could not read from file: "data/dataset_small/Blues/01 Boogie Woogie Stomp.mp3.sig"
    Yaml::loadFromFile: Could not open file: data/dataset_small/Techno and Electro/01 Bigmouth.mp3.sig
    Yaml::loadFromFile: Could not open file: data/dataset_small/Blues/01 Boogie Woogie Stomp.mp3.sig
```

I found many of those files in the folder data/yamaha_small, so I created a symlink named dataset_small pointing to yamaha_small. This doesn't completely solve the problem, but allows almost all tests to pass. Repeatedly running the tests improves the results, but one tests still fails.

Here's a full log of the tests (after creating the symlink): 
https://gist.github.com/bxdpxndx/9737934

Thank you very much!

**Comment by sildeag** [comment]
Problem fixed.  I reloaded the compressed dataset with the corrected names and this issue will go away when my fork is merged.

**Comment by alastair** [comment]
Closing this in favour of #103, which has a bit more discussion about how to fix the issue. Thanks for the original report!
