### ISSUE TITLE
Error in ./waf install on ubuntu 14.04

### ISSUE THREAD

**Issue by franc00018** [MTG/gaia#30]
Hi, 

Before executing ./waf install , I needed to copy /home/francois/gaia/build/src in /home/francois/gaia/src else I would get an error:

francois@francois-ThinkCentre-M58 ~/gaia $ sudo ./waf install
Waf: Entering directory `/home/francois/gaia/build'
→ building from /home/francois/gaia
Could not find 'libgaia2.a' in /home/francois/gaia/src

Looks like ./waf install is not configured with the right directory to look for the compiled files

Thanks

François Pelletier

**Comment by dbogdanov** [comment]
I cannot reproduce this issue, ```./waf install``` looks in a correct directory and works perfectly well for me.
