### ISSUE TITLE
Not able to use gaia2 in python

### ISSUE THREAD

**Issue by kartikgupta0909** [MTG/gaia#32]
While configuring gaia2 in ubuntu15.04 using the ./waf configure [--with-python-bindings], although it says built successfully, but also prints the line "No function [--with-python-bindings] defined in /home/kartik/open_source/acoustic_server/gaia/wscript" in the end and I am not able to install gaia2 in python, it simply gives an import error.

**Comment by kartikgupta0909** [comment]
Output of the configure command : https://gist.github.com/kartikgupta0909/830203a7926de893eae3

**Comment by alastair** [comment]
use `--with-python-bindings` without square brackets
