### ISSUE TITLE
Report test/train splits for n-fold cross-validation when training models

### ISSUE THREAD

**Issue by dbogdanov** [MTG/gaia#33]
For better reproducibility, the [`evaluateNfold`](https://github.com/MTG/gaia/blob/master/src/bindings/pygaia/classification/evaluation.py#L67) method should report point ids for test/train splits for each fold (as a json dictionary).

**Comment by dbogdanov** [comment]
We now store the seed used for the random test/train splits, so this should be enough for now.

**Comment by pabloEntropia** [comment]
Just for clarity, after this [commit](https://github.com/MTG/gaia/pull/86/commits/f5198770f18bfab0b1459d23c396e00e40e3a1e5) the splits are reported by storing a dictionary inside the confusion matrix that maps each track id to the fold in which it was part of the test set.
