### ISSUE TITLE
Report mean and stdev for accuracies of trained classifiers

### ISSUE THREAD

**Issue by dbogdanov** [MTG/gaia#34]
Provide stdev for accuracies of trained classifiers in addition to mean across folds  when reporting n-fold cross-validation results. Currently, accuracy is computed from the overall confusion matrix which is a sum of confusion matrices for each fold. 

The `evaluateNfold` should gather all confusion matrices apart in a list and return that list.

**Comment by alastair** [comment]
Is this the same as #21 ?

**Comment by dbogdanov** [comment]
Implemented in 49517aa2d9ac5244cd7afccfabbba12a61f7a009 (PR #86)

**Comment by dbogdanov** [comment]
We won't store confusion matrices for each train/test split in cross-fold validation, as they clutter results output. The split can now be reproduced as we store the seed used for the random split.
