### ISSUE TITLE
When running ./waf configure: SyntaxError: invalid syntax  except Exception, e:  

### ISSUE THREAD

**Issue by rcrath** [MTG/gaia#38]
I am taking a wild guess that this might have something to do with me having python3 as default, only because that has caused trouble other times.  Also, are the various config options explained anywhere?  If they are in the ./waf --help command, that fails with the same error.

Here is the error:
```
[gaia]$./waf configure --download 
Waf: The wscript in '/home/rich/gaia' is unreadable
Traceback (most recent call last):
  File "/home/rich/gaia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 87, in waf_entry_point
    set_main_module(Context.run_dir+os.sep+Context.WSCRIPT_FILE)
  File "/home/rich/gaia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 112, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/home/rich/gaia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Context.py", line 281, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/home/rich/gaia/wscript", line 15
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by alastair** [comment]
Did you fix this by using python2 to configure gaia? It looks like you managed to get essentia compiled correctly https://github.com/MTG/essentia/issues/387
Note that the python bindings for essentia also do not work with python3. You will need to use python2 if you want to use gaia and essentia from python.

**Comment by rcrath** [comment]
Hi I am traveling and don't have access to the machine where I was working on this.  I think the python switch may work.  will close this and reopen if I have trouble later.  thanks!

**Comment by Pysis868** [comment]
Update the script line in `waf` to specifically reference `python2`.
