### ISSUE TITLE
Configuration failed on static builds 

### ISSUE THREAD

**Issue by bd117** [MTG/gaia#45]
Hello,

I guess maybe gaia has something wrong. The message shows as below:
root@lance-virtual-machine:~/Desktop/ess# ./waf configure --with-static-examples
Setting top to                           : /mnt/hgfs/ess 
Setting out to                           : /mnt/hgfs/ess/build 
→ configuring the project in /mnt/hgfs/ess
→ Building in release mode
→ Compiling with static examples on Linux: search for pre-built dependencies in 'packaging/debian'
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'libavcodec' >= 53.25.0     : yes 
Checking for 'libavformat'               : yes 
Checking for 'libavutil'                 : yes 
Checking for 'libswresample'             : not found 
Checking for 'fftw3f'                    : yes 
Checking for 'samplerate'                : not found 
The configuration failed
(complete log in /mnt/hgfs/ess/build/config.log)
Does anybody meet the same problem? Thanks.

**Comment by alastair** [comment]
This should be reported in https://github.com/MTG/essentia/, not in gaia
