### ISSUE TITLE
Where is the "external process gaiafusion" in the gaiaLib?

### ISSUE THREAD

**Issue by djb2017** [MTG/gaia#53]
![image](https://cloud.githubusercontent.com/assets/20794222/18429692/6f120174-7907-11e6-8770-6cdc184ed873.png)

**Comment by djb2017** [comment]
![image](https://cloud.githubusercontent.com/assets/20794222/18429665/4ae7425a-7907-11e6-8bff-98683a0e2e0a.png)

**Comment by dbogdanov** [comment]
On Linux  it is installed when running ```./waf install```. However it seems we have to test if that works on Windows too.
