### ISSUE TITLE
Where to get the original dataset for trainning the SVM models?

### ISSUE THREAD

**Issue by djb2017** [MTG/gaia#54]
Hello,
There are a little difference between accuracy when using the model from http://essentia.upf.edu/documentation/svm_models/ to classify music my own.
So , please tell me where to get the original dataset for trainning the SVM models so that i can make some   
contrast.
Thanks!

**Comment by dbogdanov** [comment]
You will have to build your own datasets for training SVM models. Depending on your goal, there are some annotated audio collections for some classification tasks. Once you have an audio collection, you can analyze it using Essentia music extractor and then [train your own model](http://essentia.upf.edu/documentation/FAQ.html#training-and-running-classifier-models-in-gaia).

If you are working with music, another option is to [create your dataset](https://acousticbrainz.org/datasets/create) and train model using  AcousticBrainz (no programming required).
