### ISSUE TITLE
Brew install gaia does not work on macOS Sierra

### ISSUE THREAD

**Issue by baturayo** [MTG/gaia#57]
I upgraded my mac to Sierra and I can't install gaia via homebrew. I wrote "brew install gaia" and I received the message below. Do you have any recommendations?

"qt: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
"

**Comment by alastair** [comment]
Unfortunately, if QT does not build on Sierra then you won't be able to install gaia. We plan to remove QT as a dependency, but this is low on our priority list (https://github.com/MTG/gaia/issues/31)

I think the best solution we can offer is that you compile it on OSX and copy the files to macOS, sorry.

**Comment by dbogdanov** [comment]
There is a workaround to install qt4 on Sierra: 
http://stackoverflow.com/questions/39690404/brew-install-qt-does-not-work-on-macos-sierra

Works for me:
```
brew install cartr/qt4/qt
```
