### ISSUE TITLE
Building Error on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by muratcancicek** [MTG/gaia#59]
First of all, I would like to apologize for using here since it is probably not a real issue, I think I'm doing something wrong.
I am Muratcan from Turkey. I have to use Gaia and Essentia tools for a specific project. Since I am disabled and my adaptive tools work on only Windows, I need to figure out a way to install your tools on my Windows 10. As the installation page suggests, I am trying to use new feature of Windows 10. 
When I run the configure command, it savs qmake4, uic-qt3, and rcc-qt4 are not found together with Qt_debug packages. I know that Qt_debug packages are not necessary to build but I am not sure about the first three packages. By the way, I have Anaconda2 installed on my machine and some qt tools found under Anaconda2.Could this be my problem? I am not sure whether I have properly installed qt on the machine or not.
When I try to build, after many unused variable warnings, it gives me following error that I cannot understand. Now, I am downloading Qt for Windows to try the QtCreator projects inside the packaging/win32 directory but you say they are not tested yet.
Any help will be appreciated.
Thank you,
Muratcan 
[Gaia waf configure output.txt](https://github.com/MTG/gaia/files/765188/Gaia.waf.configure.output.txt)

Waf: Leaving directory `/mnt/d/Slow_Storage/Program_Files/Music_Libraries/gaia/build'
Build failed
 -> task in 'gaia2' failed (exit status 1):
        {task 140222829040976: qxx gaia.cpp -> gaia.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-I/mnt/d/Slow_Storage/Program_Files/Music_Libraries/gaia/build/src', '-I/mnt/d/Slow_Storage/Program_Files/Music_Libraries/gaia/src', '-I/mnt/d/Slow_Storage/Program_Files/Music_Libraries/gaia/build/src/metrics', '-I/mnt/d/Slow_Storage/Program_Files/Music_Libraries/gaia/src/metrics', '-I/mnt/d/Slow_Storage/Program_Files/Music_Libraries/gaia/build/src/3rdparty', '-I/mnt/d/Slow_Storage/Program_Files/Music_Libraries/gaia/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-I/usr/include/qt4/QtNetwork', '-DGAIA_VERSION="2.4.4\r"', '-DGAIA_GIT_SHA="v2.4.4-40-gbb4a8e7-dirty"', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '-DHAVE_QTNETWORK=1', '-DQT_SHARED', '../src/gaia.cpp', '-c', '-o', '/mnt/d/Slow_Storage/Program_Files/Music_Libraries/gaia/build/src/gaia.cpp.1.o']

**Comment by sildeag** [comment]
Another option might be using `msys64`and `mingw64_shell.bat`.  Waf build worked for me in the shell console but it is untested also.

**Comment by alastair** [comment]
based on the configure output, this appears to be related to a conflict with Anaconda. Please open if you have more information
