### ISSUE TITLE
Configuration complete, build failed!

### ISSUE THREAD

**Issue by laag115** [MTG/gaia#61]
I am on Ubuntu 16.10
I cloned from git, upgraded SWIG to 3.0.12, and installed all other dependencies
The waf configure ran perfectly fine, displaying

Setting top to                           : /usr/bin/gaia 
Setting out to                           : /usr/bin/gaia/build 
→ configuring the project in /usr/bin/gaia
→ Building in release mode
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for 'yaml-0.1'                  : yes 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for program 'qmake-qt4'         : /usr/bin/qmake-qt4 
Checking for program 'qmake4'            : not found 
Checking for program 'qmake'             : /usr/bin/qmake 
Checking for program 'uic-qt3'           : not found 
Checking for program 'uic3'              : /usr/bin/uic3 
Checking for program 'uic-qt4'           : /usr/bin/uic-qt4 
Checking for uic version                 : version 4.8.7 
Checking for program 'moc-qt4'           : /usr/bin/moc-qt4 
Checking for program 'rcc-qt4'           : not found 
Checking for program 'rcc'               : /usr/bin/rcc 
Checking for program 'lrelease-qt4'      : /usr/bin/lrelease-qt4 
Checking for program 'lupdate-qt4'       : /usr/bin/lupdate-qt4 
Found the Qt4 libraries in               : /usr/lib/x86_64-linux-gnu 
Checking for pkg-config version >= '0.1' : yes 
Checking for 'QtCore_debug'              : not found 
Checking for 'QtGui_debug'               : not found 
Checking for 'QtUiTools_debug'           : not found 
Checking for 'QtNetwork_debug'           : not found 
Checking for 'QtOpenGL_debug'            : not found 
Checking for 'QtSql_debug'               : not found 
Checking for 'QtSvg_debug'               : not found 
Checking for 'QtTest_debug'              : not found 
Checking for 'QtXml_debug'               : not found 
Checking for 'QtXmlPatterns_debug'       : not found 
Checking for 'QtWebKit_debug'            : not found 
Checking for 'Qt3Support_debug'          : not found 
Checking for 'QtHelp_debug'              : not found 
Checking for 'QtScript_debug'            : not found 
Checking for 'QtDeclarative_debug'       : not found 
Checking for 'QtDesigner_debug'          : not found 
Checking for 'QtCore'                    : yes 
Checking for 'QtGui'                     : yes 
Checking for 'QtUiTools'                 : yes 
Checking for 'QtNetwork'                 : yes 
Checking for 'QtOpenGL'                  : not found 
Checking for 'QtSql'                     : yes 
Checking for 'QtSvg'                     : yes 
Checking for 'QtTest'                    : yes 
Checking for 'QtXml'                     : yes 
Checking for 'QtXmlPatterns'             : yes 
Checking for 'QtWebKit'                  : not found 
Checking for 'Qt3Support'                : yes 
Checking for 'QtHelp'                    : yes 
Checking for 'QtScript'                  : yes 
Checking for 'QtDeclarative'             : yes 
Checking for 'QtDesigner'                : yes 
Checking for program 'swig'              : /usr/bin/swig 
Checking for program 'python'            : /usr/bin/python 
Checking for swig version                : 3.0.12 
Checking for python version              : (2, 7, 12, 'final', 0) 
python-config                            : /usr/bin/python-config 
Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes 
Testing pyembed configuration                                      : yes 
Asking python-config for pyext '--cflags --libs --ldflags' flags   : yes 
Testing pyext configuration                                        : yes 
'configure' finished successfully (0.688s)

However, running ./waf comes up with a giant wall of error that starts with

Build failed
 -> task in 'gaia2' failed (exit status 1): 
	{task 139701185517200: qxx convert.cpp -> convert.cpp.1.o

I checked config.log but the only thing that seems to be out of place is the QT tools not being found, which was expected because they weren't found during config.

Has anyone else run into this error? How did you fix it?

Thanks for the help

**Comment by alastair** [comment]
We can't help if you don't tell us what is in this "giant wall of text". The specific error will be contained in this text, and without it we can only guess what your problem may be.

**Comment by laag115** [comment]
Right thanks, heres the full error:

Build failed
 -> task in 'gaia2' failed (exit status 1): 
	{task 139636684684304: qxx convert.cpp -> convert.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-I/home/luis/Downloads/gaia/build/src', '-I/home/luis/Downloads/gaia/src', '-I/home/luis/Downloads/gaia/build/src/metrics', '-I/home/luis/Downloads/gaia/src/metrics', '-I/home/luis/Downloads/gaia/build/src/3rdparty', '-I/home/luis/Downloads/gaia/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-I/usr/include/qt4/QtNetwork', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="v2.4.4-40-gbb4a8e7"', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '-DHAVE_QTNETWORK=1', '-DQT_SHARED', '../src/convert.cpp', '-c', '-o', '/home/luis/Downloads/gaia/build/src/convert.cpp.1.o']
 -> task in 'gaia2' failed (exit status 1): 
	{task 139636684684368: qxx dataset.cpp -> dataset.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-I/home/luis/Downloads/gaia/build/src', '-I/home/luis/Downloads/gaia/src', '-I/home/luis/Downloads/gaia/build/src/metrics', '-I/home/luis/Downloads/gaia/src/metrics', '-I/home/luis/Downloads/gaia/build/src/3rdparty', '-I/home/luis/Downloads/gaia/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-I/usr/include/qt4/QtNetwork', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="v2.4.4-40-gbb4a8e7"', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '-DHAVE_QTNETWORK=1', '-DQT_SHARED', '../src/dataset.cpp', '-c', '-o', '/home/luis/Downloads/gaia/build/src/dataset.cpp.1.o']

**Comment by amigabill** [comment]
Build fails for me as well. I already compiled and installed swig 3.0.13 from github. Running Kubuntu 16.10 64bit inside of Virtualbox.

No errors from 
./autogen.sh && ./configure && make


./waf --with-python-bindings --with-stlfacade

(Much truncated)

../src/searchspacepool_impl.h:125:5: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
     for (ie=0; ie<steps.size(); ie++)    if (steps[ie] >= end) break;    ie = qMin(ie, steps.size()-1);
     ^~~
../src/searchspacepool_impl.h:125:74: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
     for (ie=0; ie<steps.size(); ie++)    if (steps[ie] >= end) break;    ie = qMin(ie, steps.size()-1);
                                                                          ^~
In file included from /home/billt/projects/gaia/src/3rdparty/Eigen/Core:279:0,
                 from /home/billt/projects/gaia/src/3rdparty/Eigen/Dense:1,
                 from ../src/types.h:26,
                 from ../src/descriptor.h:24,
                 from ../src/convert.h:26,
                 from ../src/convert.cpp:20:
/home/billt/projects/gaia/src/3rdparty/Eigen/src/Core/DenseCoeffsBase.h: In instantiation of ‘class Eigen::DenseCoeffsBase<Eigen::Matrix<float, 1, -1>, 0>’:
/home/billt/projects/gaia/src/3rdparty/Eigen/src/Core/DenseCoeffsBase.h:287:7:   required from ‘class Eigen::DenseCoeffsBase<Eigen::Matrix<float, 1, -1>, 1>’
/home/billt/projects/gaia/src/3rdparty/Eigen/src/Core/DenseCoeffsBase.h:649:7:   required from ‘class Eigen::DenseCoeffsBase<Eigen::Matrix<float, 1, -1>, 3>’
/home/billt/projects/gaia/src/3rdparty/Eigen/src/Core/util/XprHelper.h:364:8:   required from ‘struct Eigen::internal::special_scalar_op_base<Eigen::Matrix<float, 1, -1>, float, float, false>’
/home/billt/projects/gaia/src/3rdparty/Eigen/src/Core/DenseBase.h:44:34:   required from ‘class Eigen::DenseBase<Eigen::Matrix<float, 1, -1> >’
/home/billt/projects/gaia/src/3rdparty/Eigen/src/Core/MatrixBase.h:61:34:   required from ‘class Eigen::MatrixBase<Eigen::Matrix<float, 1, -1> >’
/home/billt/projects/gaia/src/3rdparty/Eigen/src/Core/PlainObjectBase.h:52:7:   required from ‘class Eigen::PlainObjectBase<Eigen::Matrix<float, 1, -1> >’
/home/billt/projects/gaia/src/3rdparty/Eigen/src/Core/Matrix.h:140:7:   required from ‘class Eigen::Matrix<float, 1, -1>’
/home/billt/projects/gaia/src/metrics/frozendistance.h:38:52:   required from here
/home/billt/projects/gaia/src/3rdparty/Eigen/src/Core/DenseCoeffsBase.h:69:30: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<float>::type {aka __vector(4) float}’ [-Wignored-attributes]
                      >::type PacketReturnType;
                              ^~~~~~~~~~~~~~~~

Waf: Leaving directory `/home/billt/projects/gaia/build'
Build failed
 -> task in 'gaia2' failed (exit status 1): 
        {task 139624521388368: qxx convert.cpp -> convert.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-DNDEBUG', '-DQT_NO_DEBUG', '-I/home/billt/projects/gaia/build/src', '-I/home/billt/projects/gaia/src', '-I/home/billt/projects/gaia/build/src/metrics', '-I/home/billt/projects/gaia/src/metrics', '-I/home/billt/projects/gaia/build/src/3rdparty', '-I/home/billt/projects/gaia/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="v2.4.4-40-gbb4a8e7"', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '../src/convert.cpp', '-c', '-o', '/home/billt/projects/gaia/build/src/convert.cpp.1.o']

**Comment by laag115** [comment]
I have tried compiling again on a different machine now the building stops at step [ 8/103]
Waf: Entering directory `/home/luis/Downloads/gaia/build'
→ building from /home/luis/Downloads/gaia
[  1/103] Compiling src/convert.cpp
[  2/103] Compiling src/dataset.cpp
[  3/103] Compiling src/debugging.cpp
[  4/103] Compiling src/descriptortree.cpp
[  5/103] Compiling src/frozendataset.cpp
[  6/103] Compiling src/gaia.cpp
[  7/103] Compiling src/gaiamath.cpp
[  8/103] Compiling src/linalg.cpp

Leaving me with this error:

Build failed
 -> task in 'gaia2' failed (exit status 1): 
	{task 140090034651984: qxx debugging.cpp -> debugging.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-I/home/luis/Downloads/gaia/build/src', '-I/home/luis/Downloads/gaia/src', '-I/home/luis/Downloads/gaia/build/src/metrics', '-I/home/luis/Downloads/gaia/src/metrics', '-I/home/luis/Downloads/gaia/build/src/3rdparty', '-I/home/luis/Downloads/gaia/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-I/usr/include/qt4/QtNetwork', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="v2.4.4-40-gbb4a8e7"', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '-DHAVE_QTNETWORK=1', '-DQT_SHARED', '../src/debugging.cpp', '-c', '-o', '/home/luis/Downloads/gaia/build/src/debugging.cpp.1.o']
 -> task in 'gaia2' failed (exit status 1): 
	{task 140090034652816: qxx gaiamath.cpp -> gaiamath.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-I/home/luis/Downloads/gaia/build/src', '-I/home/luis/Downloads/gaia/src', '-I/home/luis/Downloads/gaia/build/src/metrics', '-I/home/luis/Downloads/gaia/src/metrics', '-I/home/luis/Downloads/gaia/build/src/3rdparty', '-I/home/luis/Downloads/gaia/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-I/usr/include/qt4/QtNetwork', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="v2.4.4-40-gbb4a8e7"', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '-DHAVE_QTNETWORK=1', '-DQT_SHARED', '../src/gaiamath.cpp', '-c', '-o', '/home/luis/Downloads/gaia/build/src/gaiamath.cpp.1.o']
 -> task in 'gaia2' failed (exit status 1): 
	{task 140090034652496: qxx descriptortree.cpp -> descriptortree.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-I/home/luis/Downloads/gaia/build/src', '-I/home/luis/Downloads/gaia/src', '-I/home/luis/Downloads/gaia/build/src/metrics', '-I/home/luis/Downloads/gaia/src/metrics', '-I/home/luis/Downloads/gaia/build/src/3rdparty', '-I/home/luis/Downloads/gaia/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-I/usr/include/qt4/QtNetwork', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="v2.4.4-40-gbb4a8e7"', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '-DHAVE_QTNETWORK=1', '-DQT_SHARED', '../src/descriptortree.cpp', '-c', '-o', '/home/luis/Downloads/gaia/build/src/descriptortree.cpp.1.o']
 -> task in 'gaia2' failed (exit status 1): 
	{task 140090034652048: qxx convert.cpp -> convert.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-I/home/luis/Downloads/gaia/build/src', '-I/home/luis/Downloads/gaia/src', '-I/home/luis/Downloads/gaia/build/src/metrics', '-I/home/luis/Downloads/gaia/src/metrics', '-I/home/luis/Downloads/gaia/build/src/3rdparty', '-I/home/luis/Downloads/gaia/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-I/usr/include/qt4/QtNetwork', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="v2.4.4-40-gbb4a8e7"', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '-DHAVE_QTNETWORK=1', '-DQT_SHARED', '../src/convert.cpp', '-c', '-o', '/home/luis/Downloads/gaia/build/src/convert.cpp.1.o']
 -> task in 'gaia2' failed (exit status 1): 
	{task 140090034652688: qxx gaia.cpp -> gaia.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-I/home/luis/Downloads/gaia/build/src', '-I/home/luis/Downloads/gaia/src', '-I/home/luis/Downloads/gaia/build/src/metrics', '-I/home/luis/Downloads/gaia/src/metrics', '-I/home/luis/Downloads/gaia/build/src/3rdparty', '-I/home/luis/Downloads/gaia/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-I/usr/include/qt4/QtNetwork', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="v2.4.4-40-gbb4a8e7"', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '-DHAVE_QTNETWORK=1', '-DQT_SHARED', '../src/gaia.cpp', '-c', '-o', '/home/luis/Downloads/gaia/build/src/gaia.cpp.1.o']
 -> task in 'gaia2' failed (exit status 1): 
	{task 140090034652624: qxx frozendataset.cpp -> frozendataset.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-I/home/luis/Downloads/gaia/build/src', '-I/home/luis/Downloads/gaia/src', '-I/home/luis/Downloads/gaia/build/src/metrics', '-I/home/luis/Downloads/gaia/src/metrics', '-I/home/luis/Downloads/gaia/build/src/3rdparty', '-I/home/luis/Downloads/gaia/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-I/usr/include/qt4/QtNetwork', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="v2.4.4-40-gbb4a8e7"', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '-DHAVE_QTNETWORK=1', '-DQT_SHARED', '../src/frozendataset.cpp', '-c', '-o', '/home/luis/Downloads/gaia/build/src/frozendataset.cpp.1.o']
 -> task in 'gaia2' failed (exit status 1): 
	{task 140090034652176: qxx dataset.cpp -> dataset.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-I/home/luis/Downloads/gaia/build/src', '-I/home/luis/Downloads/gaia/src', '-I/home/luis/Downloads/gaia/build/src/metrics', '-I/home/luis/Downloads/gaia/src/metrics', '-I/home/luis/Downloads/gaia/build/src/3rdparty', '-I/home/luis/Downloads/gaia/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-I/usr/include/qt4/QtNetwork', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="v2.4.4-40-gbb4a8e7"', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '-DHAVE_QTNETWORK=1', '-DQT_SHARED', '../src/dataset.cpp', '-c', '-o', '/home/luis/Downloads/gaia/build/src/dataset.cpp.1.o']
 -> task in 'gaia2' failed (exit status 1): 
	{task 140090034652944: qxx linalg.cpp -> linalg.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-I/home/luis/Downloads/gaia/build/src', '-I/home/luis/Downloads/gaia/src', '-I/home/luis/Downloads/gaia/build/src/metrics', '-I/home/luis/Downloads/gaia/src/metrics', '-I/home/luis/Downloads/gaia/build/src/3rdparty', '-I/home/luis/Downloads/gaia/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-I/usr/include/qt4/QtNetwork', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="v2.4.4-40-gbb4a8e7"', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '-DHAVE_QTNETWORK=1', '-DQT_SHARED', '../src/linalg.cpp', '-c', '-o', '/home/luis/Downloads/gaia/build/src/linalg.cpp.1.o']

Both times the error has come from a file with the extension ".cpp" which I noticed are in the gaia/packaging/darwin/Gaia2lib/Gaia2lib.pro file, but I don't know what is causing the error.

**Comment by laag115** [comment]
My failed builds were all on Ubuntu 16.10 Yakety Yak.
Solved the problem with a fresh install of Ubuntu 14.04.5 Trusty Tahr!
