### ISSUE TITLE
build failed on Raspbian

### ISSUE THREAD

**Issue by snape6666** [MTG/gaia#63]
i tried the maser and the swig-fix... but both dont work... What is the problem?

sudo ./waf
Waf: Entering directory `/home/pi/Downloads/gaia-swig_fix/build'
→ building from /home/pi/Downloads/gaia-swig_fix
[ 1/90] Compiling src/convert.cpp
g++: error: unrecognized command line option ‘-msse2’

Waf: Leaving directory `/home/pi/Downloads/gaia-swig_fix/build'
Build failed
 -> task in 'gaia2' failed (exit status 1): 
	{task 1985144784: qxx convert.cpp -> convert.cpp.1.o}
['/usr/bin/g++', '-Wall', '-fno-strict-aliasing', '-fPIC', '-fvisibility=hidden', '-O2', '-msse2', '-DNDEBUG', '-DQT_NO_DEBUG', '-I/home/pi/Downloads/gaia-swig_fix/build/src', '-I/home/pi/Downloads/gaia-swig_fix/src', '-I/home/pi/Downloads/gaia-swig_fix/build/src/metrics', '-I/home/pi/Downloads/gaia-swig_fix/src/metrics', '-I/home/pi/Downloads/gaia-swig_fix/build/src/3rdparty', '-I/home/pi/Downloads/gaia-swig_fix/src/3rdparty', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="Undefined"', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '../src/convert.cpp', '-c', '-o', '/home/pi/Downloads/gaia-swig_fix/build/src/convert.cpp.1.o']

**Comment by alastair** [comment]
Gaia requires SSE to compile which is an intel extension and therefore not available on ARM. It may be possible to compile without it, but we are unable to support this setup.

**Comment by snape6666** [comment]
Is there a way to compile it somewhere else and start it on the raspy?

**Comment by alastair** [comment]
It may be possible to cross-compile, but there is currently no support for this in the build scripts.
