### ISSUE TITLE
'make_db_from_directory.py' missing

### ISSUE THREAD

**Issue by sildeag** [MTG/gaia#69]
Does anyone have this code?

Also, a simpler explanation of semi-metric space and its relevance to acoustic sound waves would be appreciated.

**Comment by dbogdanov** [comment]
We do not have that code. What about using `gaiamerge` or `gaiafusion` instead?

**Comment by sildeag** [comment]
I am not familiar with `gaiamerge` or `gaiafusion` so will have to look.  I left this project sometime ago and am currently spending time understanding CMake and creating Windows `dlls`
