### ISSUE TITLE
Gaia Python 2/3 issues.

### ISSUE THREAD

**Issue by sildeag** [MTG/gaia#72]
`gaia/src/bindings/pygaia/scripts/classification/project_file.py` is `python2 and python3` incompatible.  Not certain what this file does.  

`gaia/src/bindings/pygaia/scripts/classification/generate_essentia_models.py` is `python3` incompatible.  These lines are the problem.

`# moods` 
`for m in range (mood_acoustic mood_blue mood_electronic mood_furious mood_happy mood_party` `mood_relaxed; do mkdir -p $m; cd $m; python`

`for m in `ls`; do cd $m; python ../../../gaia/src/scripts/classification/run_tests.py $m.yaml; cd ..; done`

**Comment by alastair** [comment]
We've updated these files for python 3 (#84, #90) and tested them in #86
