### ISSUE TITLE
Remove Cyclops?

### ISSUE THREAD

**Issue by alastair** [MTG/gaia#91]
We should consider removing cyclops:
 - No one has used it in the 7 years that I've been here
 - Freesound doesn't use it
 - It has no documentation
 - It doesn't work with qt5 without changes
 - There are a bunch of other NN tools that we could consider using instead (should we do a comparison some time?)

**Comment by dbogdanov** [comment]
Agreed, this code isn't relevant anymore to be maintained, and if one need a similar functionality, there might be better options to use instead.
