### ISSUE TITLE
ClassificationResults can distinguish between classifier types, but isn't needed

### ISSUE THREAD

**Issue by alastair** [MTG/gaia#99]
https://github.com/MTG/gaia/blob/ec8afc589d7d70b84450ba1a400da7bd684808da/src/bindings/pygaia/scripts/classification/get_classification_results.py#L29

There is this parameter `classifierType` which is used to distinguish between the type of classifier, but we only have svm in gaia. We should remove this parameter unless we absolutely know that we're going to add more classifiers.

**Comment by alastair** [comment]
also, it seems like the filterResults method isn't used. Remove if it unneeded.

**Comment by dbogdanov** [comment]
This has been addressed in e0d8274e81180113250ed636690b8508eccd8f7d.
